/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable @typescript-eslint/no-unused-vars */
import { groq } from "@ai-sdk/groq";
import { generateObject } from "ai";
import { NextResponse } from 'next/server';
import { z } from 'zod';
import Exa from 'exa-js'; // Assuming Exa SDK is installed and configured

// --- Zod Schemas ---

// Schema for prompts generated by the AI
const searchPromptsSchema = z.object({
  prompts: z.array(z.string().describe("A realistic search query a user might type into Google, Perplexity or ChatGPT to find information about the brand."))
           .length(5) // 
           .describe("An array of 5 search queries.")
});

// Schema for Exa search result item (simplified)
const exaResultSchema = z.object({
    url: z.string().optional(),
    title: z.string().optional(),
    publishedDate: z.string().optional(),
    author: z.string().optional(),
    score: z.number().optional(),
    id: z.string().optional(),
});

// Schema for the final API response
const citationAnalysisResponseSchema = z.object({
    generated_prompts: z.array(z.string()),
    exa_results: z.array(exaResultSchema),
});

// --- Environment Variables ---
// Ensure GROQ_API_KEY and EXA_API_KEY are set in your environment

const groqApiKey = process.env.GROQ_API_KEY;
const exaApiKey = process.env.EXA_API_KEY;

if (!groqApiKey) {
  console.warn("GROQ_API_KEY environment variable not set.");
  // Potentially throw an error or handle gracefully depending on requirements
}
if (!exaApiKey) {
  console.warn("EXA_API_KEY environment variable not set.");
   // Potentially throw an error or handle gracefully depending on requirements
}

const exa = new Exa(exaApiKey); // Initialize Exa client

// --- API Route Handler ---

export async function POST(req: Request) {
  if (!groqApiKey || !exaApiKey) {
      return NextResponse.json({ error: 'API keys not configured.' }, { status: 500 });
  }

  try {
    const { brandName, brandIndustry } = await req.json();

    if (!brandName || !brandIndustry) {
      return NextResponse.json({ error: 'Missing brandName or brandIndustry in request body.' }, { status: 400 });
    }

    // 1. Generate Search Prompts using Groq (Llama 3)
    const promptGenerationPrompt = `
      Given the brand "${brandName}" operating in the "${brandIndustry}" industry, generate exactly 5 realistic search queries or prompts that potential customers, journalists, or researchers might use on Google, Perplexity or ChatGPT to find information, reviews, news, or discussions about this brand. Focus on variety (e.g., brand reputation, product searches, comparisons, news).
    `;

    const { object: generatedPromptsData } = await generateObject({
      model: groq("llama3-8b-8192"), // Using Llama 3 via Groq
      schema: searchPromptsSchema,
      prompt: promptGenerationPrompt,
    });

    const prompts = generatedPromptsData.prompts;

    // 2. Search using Exa for each prompt
    let allExaResults: z.infer<typeof exaResultSchema>[] = [];
    const resultsPerPrompt = 5; // Fetch 5 results per prompt for a total of 15

    for (const prompt of prompts) {
      try {
        const exaResponse = await exa.search(prompt, {
          numResults: resultsPerPrompt,
          type: 'keyword', // Use keyword search for broader results
          useAutoprompt: false, // Use the exact generated prompt
        });
        // Map Exa results to our schema (adapt based on actual Exa SDK response structure)
        const mappedResults = exaResponse.results.map((res: any) => ({
            url: res.url,
            title: res.title,
            publishedDate: res.publishedDate,
            author: res.author,
            score: res.score,
            id: res.id,
        }));
        allExaResults = [...allExaResults, ...mappedResults];
      } catch (exaError) {
        console.error(`Exa search failed for prompt "${prompt}":`, exaError);
        // Continue to next prompt even if one fails, or handle error differently
      }
    }

    // 3. Prepare and return response
    const responseData: z.infer<typeof citationAnalysisResponseSchema> = {
        generated_prompts: prompts,
        exa_results: allExaResults,
    };

    return NextResponse.json(responseData);

  } catch (error: unknown) {
    console.error("Error in brand citations analysis route:", error);
    const errorMessage = error instanceof Error ? error.message : 'An unexpected error occurred.';
    // Avoid leaking internal details in production errors
    return NextResponse.json({ error: 'Failed to perform citation analysis.', details: process.env.NODE_ENV === 'development' ? errorMessage : undefined }, { status: 500 });
  }
}

// Optional: Add GET handler or other methods if needed 